#!/usr/bin/env bash
KCONTEXT=$(kubectl config current-context 2>/dev/null)
if [[ $?=="0" ]]; then
    CC=$(kubectl config view -ojsonpath='{..current-context}')

    if [[ -z $CC ]]; then
        echo ""
        echo ""
        exit 0
    fi

    KNAMESPACE=$(kubectl config view -ojsonpath="{.contexts[?(@.name==\"$CC\")]..namespace}")
    echo "☸ $KCONTEXT/$KNAMESPACE ☸"
    echo "☸ $KCONTEXT/$KNAMESPACE ☸"
fi

